version: '3.1'

services:
  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: afV1O0tCjwOK!
    ports:
      - 3306:3306
  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080